### ISSUE TITLE
ModuleNotFoundError: No module named 'pysobatools.sobaeval'

### ISSUE THREAD

**Issue by naoto0804** [stevewongv/InstanceShadowDetection#1]
When I run `demo.py` after following [instruction](`PythonAPI/pysobatools/cocoeval.py`), the following error happened. 
I guess `PythonAPI/pysobatools/cocoeval.py` should be renamed to  `PythonAPI/pysobatools/sobaeval.py` ?

```
$ python demo.py --input ./demo/web-shadow0573.jpg --output ./ --config ./config/LISA_101_FPN_3x_demo.yaml
Traceback (most recent call last):
  File "demo.py", line 16, in <module>
    from predictor import VisualizationDemo
  File "/home3/inoue/experiment/relighting/InstanceShadowDetection/projects/LISA/predictor.py", line 10, in <module>
    from detectron2.engine.defaults import DefaultPredictor
  File "/home3/inoue/experiment/relighting/InstanceShadowDetection/.env/lib/python3.7/site-packages/detectron2-0.1-py3.7-linux-x86_64.egg/detectron2/engine/__init__.py", line 12, in <module>
  File "/home3/inoue/experiment/relighting/InstanceShadowDetection/.env/lib/python3.7/site-packages/detectron2-0.1-py3.7-linux-x86_64.egg/detectron2/engine/defaults.py", line 34, in <module>
    from detectron2.modeling import build_model
  File "/home3/inoue/experiment/relighting/InstanceShadowDetection/.env/lib/python3.7/site-packages/detectron2-0.1-py3.7-linux-x86_64.egg/detectron2/modeling/__init__.py", line 17, in <module>
  File "/home3/inoue/experiment/relighting/InstanceShadowDetection/.env/lib/python3.7/site-packages/detectron2-0.1-py3.7-linux-x86_64.egg/detectron2/modeling/meta_arch/__init__.py", line 6, in <module>
  File "/home3/inoue/experiment/relighting/InstanceShadowDetection/.env/lib/python3.7/site-packages/detectron2-0.1-py3.7-linux-x86_64.egg/detectron2/modeling/meta_arch/panoptic_fpn.py", line 10, in <module>
  File "/home3/inoue/experiment/relighting/InstanceShadowDetection/.env/lib/python3.7/site-packages/detectron2-0.1-py3.7-linux-x86_64.egg/detectron2/modeling/postprocessing.py", line 8, in <module>
ModuleNotFoundError: No module named 'pysobatools.sobaeval'
```

**Comment by stevewongv** [comment]
Thank you for your report!

I have fixed this in the newest commit. Please try it again. If you meet any problems, please let me know!
